#!/bin/bash
# Docker commands helper script

echo "🐳 MCP Cognitive Analyst - Docker Commands"
echo ""
echo "Build images:"
echo "  docker-compose build"
echo ""
echo "Start all services:"
echo "  docker-compose up -d"
echo ""
echo "Stop all services:"
echo "  docker-compose down"
echo ""
echo "View logs:"
echo "  docker-compose logs -f business-mcp"
echo "  docker-compose logs -f memory-mcp"
echo "  docker-compose logs -f postgres"
echo ""
echo "Access PostgreSQL:"
echo "  docker exec -it mcp-postgres psql -U postgres -d business_db"
echo ""
echo "View all services:"
echo "  docker-compose ps"
echo ""
echo "Clean up (remove volumes):"
echo "  docker-compose down -v"
